# Generated by Django 5.1.6 on 2025-02-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('faculty_code', models.CharField(max_length=50)),
                ('session', models.TextField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('min_per_session', models.IntegerField()),
                ('lecturer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=255)),
                ('resource_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('lecture', models.BooleanField(default=False)),
                ('tutorial', models.BooleanField(default=False)),
                ('lab', models.BooleanField(default=False)),
                ('workshop', models.BooleanField(default=False)),
                ('resource_status', models.CharField(max_length=50)),
            ],
        ),
    ]
